// <auto-generated />
using System;
using Chapeau.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chapeau.Infrastructure.Migrations
{
    [DbContext(typeof(ChapeauDbContext))]
    [Migration("20260716084336_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("Chapeau.Core.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tip")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Chapeau.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Role = "Waiter",
                            Status = "Active",
                            UserCode = "A001"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Bob",
                            LastName = "Smith",
                            Role = "Waiter",
                            Status = "Active",
                            UserCode = "A002"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Charlie",
                            LastName = "Brown",
                            Role = "Chef",
                            Status = "Active",
                            UserCode = "B001"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Diana",
                            LastName = "Ross",
                            Role = "Bartender",
                            Status = "Active",
                            UserCode = "C001"
                        });
                });

            modelBuilder.Entity("Chapeau.Core.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Card")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Card = "Lunch",
                            Category = "Starters",
                            Name = "Bruschetta",
                            Price = 9.50m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            Card = "Lunch",
                            Category = "Starters",
                            Name = "Caesar Salad",
                            Price = 11.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            Card = "Lunch",
                            Category = "Starters",
                            Name = "Soup of the Day",
                            Price = 8.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            Card = "Lunch",
                            Category = "Mains",
                            Name = "Grilled Chicken",
                            Price = 18.50m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            Card = "Lunch",
                            Category = "Mains",
                            Name = "Beef Burger",
                            Price = 16.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 6,
                            Card = "Lunch",
                            Category = "Mains",
                            Name = "Fish & Chips",
                            Price = 17.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 7,
                            Card = "Lunch",
                            Category = "Mains",
                            Name = "Vegetarian Pasta",
                            Price = 15.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 8,
                            Card = "Lunch",
                            Category = "Desserts",
                            Name = "Tiramisu",
                            Price = 8.50m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 9,
                            Card = "Lunch",
                            Category = "Desserts",
                            Name = "Ice Cream",
                            Price = 6.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 10,
                            Card = "Lunch",
                            Category = "Entremet",
                            Name = "Garlic Bread",
                            Price = 5.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 11,
                            Card = "Lunch",
                            Category = "Entremet",
                            Name = "Fries",
                            Price = 4.50m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 12,
                            Card = "Lunch",
                            Category = "CoffeeTea",
                            Name = "Coffee",
                            Price = 3.50m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 13,
                            Card = "Dinner",
                            Category = "Starters",
                            Name = "Oysters Kilpatrick",
                            Price = 16.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 14,
                            Card = "Dinner",
                            Category = "Starters",
                            Name = "Calamari",
                            Price = 14.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 15,
                            Card = "Dinner",
                            Category = "Starters",
                            Name = "Pâté",
                            Price = 13.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 16,
                            Card = "Dinner",
                            Category = "Mains",
                            Name = "Ribeye Steak",
                            Price = 32.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 17,
                            Card = "Dinner",
                            Category = "Mains",
                            Name = "Lamb Rack",
                            Price = 34.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 18,
                            Card = "Dinner",
                            Category = "Mains",
                            Name = "Salmon Fillet",
                            Price = 28.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 19,
                            Card = "Dinner",
                            Category = "Mains",
                            Name = "Duck Confit",
                            Price = 30.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 20,
                            Card = "Dinner",
                            Category = "Mains",
                            Name = "Vegetable Risotto",
                            Price = 22.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 21,
                            Card = "Dinner",
                            Category = "Desserts",
                            Name = "Crème Brûlée",
                            Price = 10.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 22,
                            Card = "Dinner",
                            Category = "Desserts",
                            Name = "Chocolate Lava Cake",
                            Price = 12.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 23,
                            Card = "Dinner",
                            Category = "Desserts",
                            Name = "Cheesecake",
                            Price = 10.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 24,
                            Card = "Dinner",
                            Category = "Entremet",
                            Name = "Truffle Fries",
                            Price = 8.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 25,
                            Card = "Dinner",
                            Category = "CoffeeTea",
                            Name = "Espresso Martini",
                            Price = 14.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 26,
                            Card = "Drinks",
                            Category = "Beers",
                            Name = "House Beer",
                            Price = 7.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 27,
                            Card = "Drinks",
                            Category = "Beers",
                            Name = "Craft Pale Ale",
                            Price = 9.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 28,
                            Card = "Drinks",
                            Category = "Beers",
                            Name = "Stout",
                            Price = 9.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 29,
                            Card = "Drinks",
                            Category = "Wines",
                            Name = "Shiraz",
                            Price = 10.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 30,
                            Card = "Drinks",
                            Category = "Wines",
                            Name = "Chardonnay",
                            Price = 10.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 31,
                            Card = "Drinks",
                            Category = "Wines",
                            Name = "Sauvignon Blanc",
                            Price = 10.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 32,
                            Card = "Drinks",
                            Category = "Spirit",
                            Name = "Whiskey",
                            Price = 12.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 33,
                            Card = "Drinks",
                            Category = "Spirit",
                            Name = "Vodka",
                            Price = 10.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 34,
                            Card = "Drinks",
                            Category = "Spirit",
                            Name = "Gin",
                            Price = 10.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 35,
                            Card = "Drinks",
                            Category = "Spirit",
                            Name = "Rum",
                            Price = 10.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 36,
                            Card = "Drinks",
                            Category = "CoffeeTea",
                            Name = "Cocktail - Mojito",
                            Price = 14.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 37,
                            Card = "Drinks",
                            Category = "CoffeeTea",
                            Name = "Cocktail - Margarita",
                            Price = 14.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 38,
                            Card = "Drinks",
                            Category = "Entremet",
                            Name = "Nuts Mix",
                            Price = 5.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 39,
                            Card = "Drinks",
                            Category = "Entremet",
                            Name = "Olives",
                            Price = 5.00m,
                            Stock = 30
                        });
                });

            modelBuilder.Entity("Chapeau.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TableId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Chapeau.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Chapeau.Core.Entities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            Number = 1,
                            Status = "Free"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            Number = 2,
                            Status = "Free"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            Number = 3,
                            Status = "Free"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            Number = 4,
                            Status = "Free"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4,
                            Number = 5,
                            Status = "Free"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 6,
                            Number = 6,
                            Status = "Free"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 6,
                            Number = 7,
                            Status = "Free"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 6,
                            Number = 8,
                            Status = "Free"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 8,
                            Number = 9,
                            Status = "Free"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 8,
                            Number = 10,
                            Status = "Free"
                        });
                });

            modelBuilder.Entity("Chapeau.Core.Entities.Bill", b =>
                {
                    b.HasOne("Chapeau.Core.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Chapeau.Core.Entities.Order", b =>
                {
                    b.HasOne("Chapeau.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chapeau.Core.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Chapeau.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("Chapeau.Core.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chapeau.Core.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Chapeau.Core.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
